### ISSUE TITLE
error launching etfconsole

### ISSUE THREAD

**Issue by jeretc** [Esser420/EvilTwinFramework#4]
hi i'm getting this error:

[+] Found previous session from today. Loading it.
[+] Loading last session from 14/01/2018
[+] Loading session 'et'!
Traceback (most recent call last):
  File "./etfconsole.py", line 645, in <module>
    console = ETFConsole(session_manager.get_command_history())
  File "./etfconsole.py", line 35, in __init__
    self.aircommunicator = AirCommunicator(self.configs["etf"]["aircommunicator"])
  File "./core/AirCommunicator/aircommunicator.py", line 31, in __init__
    self.air_host = AirHost(config["airhost"])
  File "./core/AirCommunicator/airhost.py", line 28, in __init__
    either by argument in the command line or in the etf.conf file")
etfexceptions.MissingConfigurationFileException: [-] Missing Configuration File:
dnsmasq and hostapd configuration files must be specified
                                                     either by argument in the command line or in the etf.conf file

**Comment by Esser420** [comment]
I posted a solution for this that worked for me:

> apt-get remove --purge python-cryptography
> pip uninstall mitmproxy
> pip3 uninstall mitmproxy
> pip install -U cryptography
> pip install mitmproxy==0.18.2

Not sure this is going to work for you. I have Kali installed on my machine (not VM).
Can you tell me what OS you are using, if it is in a VM?

I will try updating the mitmproxy package in the future, I'm only using that version because it is the last python2 compatible version, I will try porting this project to python3 and clean lots of things up.

**Comment by jeretc** [comment]
yeah i saw your solution at wifi-pumpkin site git. that didn't work. I'm using a VM running Parrotsec.

**Comment by Esser420** [comment]
Hmm I'm also finding that the first error is strange.. The first error appears after the imports nad it should have errored before. 

How did you install things? did you use the setup script?

I've opened a couple of issues since there are a couple of things that might not work for most people and just and complications when trying to work with the tool.

**Comment by jeretc** [comment]
The error is strange indeed. Yea i did use the setup script.. yea would be great if could use eviltwinF with the portal.

**Comment by Esser420** [comment]
This is probaly going to take me a little while to debug since I started working recently and time free time is short. I will try to get it running on a ParrotSec VM.

**Comment by jeretc** [comment]
Hi any updates on this?

**Comment by lacuta** [comment]
I installed it on kali VM everything was fine, but when I run ./etfconsole.py I get an error file ./etfconsole.py line 3 in modules from termcolore import colored.
Any help please

**Comment by Esser420** [comment]
@lacuta try installing termcolor
`pip install termcolor`

@jeretc thanks for still showing interest in the project. I haven't used any of my free time to maintain this project to be honest and after all this time I realised that I did some very naive things in this project and that my programming skills have grown a lot. I'm thinking of doing a big rewrite of this project to make it much more portable and easy to install/run.

**Comment by jeretc** [comment]
@Esser420 good to know..

**Comment by kookyei** [comment]
Please help me can't. It keep giving me errors I've tried everything. It says: 
Traceback (most recent call last):
  File "./etfconsole.py", line 13, in <module>
    from AirCommunicator.aircommunicator import AirCommunicator
  File "./core/AirCommunicator/aircommunicator.py", line 15, in <module>
    from Plugins.credentialsniffer import CredentialSniffer
  File "./core/Plugins/credentialsniffer.py", line 17, in <module>
    from scapy.all import Ether, Dot11Beacon, EAPOL, EAP, LEAP, PcapWriter, sniff, bind_layers
ImportError: cannot import name LEAP

**Comment by voldemort2000** [comment]
> @lacuta try installing termcolor
> `pip install termcolor`
> 
> @jeretc thanks for still showing interest in the project. I haven't used any of my free time to maintain this project to be honest and after all this time I realised that I did some very naive things in this project and that my programming skills have grown a lot. I'm thinking of doing a big rewrite of this project to make it much more portable and easy to install/run.

It says it is already installed ... ETF seems to be incompatible with Kali 2020.4

**Comment by gabriele-costa** [comment]
> Please help me can't. It keep giving me errors I've tried everything. It says:
> Traceback (most recent call last):
> File "./etfconsole.py", line 13, in
> from AirCommunicator.aircommunicator import AirCommunicator
> File "./core/AirCommunicator/aircommunicator.py", line 15, in
> from Plugins.credentialsniffer import CredentialSniffer
> File "./core/Plugins/credentialsniffer.py", line 17, in
> from scapy.all import Ether, Dot11Beacon, EAPOL, EAP, LEAP, PcapWriter, sniff, bind_layers
> ImportError: cannot import name LEAP

Very same error on ubuntu 20.04. Any suggestion on how to solve it? Thanks
